#
#
#
name: 'Composite actions Docker login'
description: 'docker login'

inputs:
  username:
    description: 'username'
    required: true
  password:
    description: 'password or token'
    required: true
runs:
    using: 'composite'
    steps:    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}