
#
#
#
name: 'Composite actions Vault Get K/V'
description: 'Get K/V from vault'

inputs:
  url:
    description: 'Url vault'
    required: true
  caCertificate:
    description: 'CA Cert vault.'
    required: false
  username:
    description: 'Username to authenticate vault'
    required: true
  password: 
    description: 'Password to authenticate vault'
    required: true
runs:
    using: 'composite'
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }} # VAULT_URL
          caCertificate: ${{ secrets.VAULT_CA_CERT }} # VAULT_CA_CERT
          method: userpass
          username: ${{ secrets.VAULT_USERNAME }} # VAULT_USERNAME
          password: ${{ secrets.VAULT_PASSWORD }} # VAULT_PASSWORD