
#
#
#
name: 'Composite actions Vault Get K/V'
description: 'Get K/V from vault'

inputs:
  vault_url:
    description: 'Url vault'
    required: true
  caCertificate:
    description: 'CA Cert vault.'
    required: false
  vault_username:
    description: 'Username to authenticate vault'
    required: true
  vault_password: 
    description: 'Password to authenticate vault'
    required: true
runs:
    using: 'composite'
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.vault_url }}
          caCertificate: ${{ inputs.caCertificate }}
          method: userpass
          username: ${{ inputs.vault_username }} 
          password: ${{ inputs.vault_password }}